import { Node, Edge } from '@xyflow/react';
import { BuildArchitecture, BuildArchitectureNode, BuildArchitectureEdge, BlockType } from '../types/lego';

export function generateAppArchitecture(nodes: Node[], edges: Edge[]): BuildArchitecture {
  const nodeMap = new Map<string, Node>();
  nodes.forEach((n) => nodeMap.set(n.id, n));

  // Determine incoming & outgoing connections per node
  const inDegree: Record<string, number> = {};
  const outDegree: Record<string, number> = {};
  const inEdgesMap: Record<string, string[]> = {};
  const outEdgesMap: Record<string, string[]> = {};

  nodes.forEach((n) => {
    inDegree[n.id] = 0;
    outDegree[n.id] = 0;
    inEdgesMap[n.id] = [];
    outEdgesMap[n.id] = [];
  });

  edges.forEach((e) => {
    if (outDegree[e.source] !== undefined) {
      outDegree[e.source]++;
      outEdgesMap[e.source].push(e.target);
    }
    if (inDegree[e.target] !== undefined) {
      inDegree[e.target]++;
      inEdgesMap[e.target].push(e.source);
    }
  });

  // Entry points (no inputs) and terminal points (no outputs)
  const entryPoints = nodes.filter((n) => inDegree[n.id] === 0).map((n) => n.id);
  const terminalPoints = nodes.filter((n) => outDegree[n.id] === 0).map((n) => n.id);

  // Compute topological pipeline stages
  const visited = new Set<string>();
  const pipelineStages: { stage: number; nodeIds: string[] }[] = [];
  let currentStageNodes = [...entryPoints];
  let stageIndex = 1;

  while (currentStageNodes.length > 0 && visited.size < nodes.length) {
    const stageItems: string[] = [];
    const nextCandidates = new Set<string>();

    for (const nid of currentStageNodes) {
      if (!visited.has(nid)) {
        visited.add(nid);
        stageItems.push(nid);
        (outEdgesMap[nid] || []).forEach((targetId) => {
          nextCandidates.add(targetId);
        });
      }
    }

    if (stageItems.length > 0) {
      pipelineStages.push({
        stage: stageIndex++,
        nodeIds: stageItems,
      });
    }

    currentStageNodes = Array.from(nextCandidates).filter((id) => !visited.has(id));
  }

  // Handle any remaining disconnected or cyclic nodes
  const unvisited = nodes.filter((n) => !visited.has(n.id)).map((n) => n.id);
  if (unvisited.length > 0) {
    pipelineStages.push({
      stage: stageIndex,
      nodeIds: unvisited,
    });
  }

  // Count block types
  const blockTypesCount: Record<string, number> = {};
  nodes.forEach((n) => {
    const t = (n.type as BlockType) || 'unknown';
    blockTypesCount[t] = (blockTypesCount[t] || 0) + 1;
  });

  // Map to clean structured node representation
  const structuredNodes: BuildArchitectureNode[] = nodes.map((n) => {
    const nodeData = n.data as any;
    return {
      id: n.id,
      type: (n.type as BlockType) || 'login',
      label: nodeData.title || n.id,
      config: nodeData.config || {},
      inputs: edges.filter((e) => e.target === n.id).map((e) => `${e.source}${e.sourceHandle ? `:${e.sourceHandle}` : ''}`),
      outputs: edges.filter((e) => e.source === n.id).map((e) => `${e.target}${e.targetHandle ? `:${e.targetHandle}` : ''}`),
      status: 'ready',
    };
  });

  // Map edges
  const structuredEdges: BuildArchitectureEdge[] = edges.map((e) => ({
    id: e.id,
    fromNode: e.source,
    fromHandle: e.sourceHandle || null,
    toNode: e.target,
    toHandle: e.targetHandle || null,
    label: (e.data as any)?.label || undefined,
  }));

  const architecture: BuildArchitecture = {
    version: '1.0.0-lego',
    appName: 'Software Lego Application',
    generatedAt: new Date().toISOString(),
    summary: {
      totalBlocks: nodes.length,
      totalConnections: edges.length,
      entryPoints,
      terminalPoints,
      pipelineStages: pipelineStages.length,
      blockTypesCount,
    },
    executionPipeline: pipelineStages,
    nodes: structuredNodes,
    edges: structuredEdges,
    rawGraph: {
      nodeCount: nodes.length,
      edgeCount: edges.length,
    },
  };

  return architecture;
}

export function generateBackendCode(arch: BuildArchitecture): string {
  return `/**
 * Generated by Software Lego Builder v${arch.version}
 * Timestamp: ${arch.generatedAt}
 * Total Blocks: ${arch.summary.totalBlocks} | Pipeline Stages: ${arch.summary.pipelineStages}
 */

import express, { Request, Response } from 'express';

const app = express();
app.use(express.json());

// Application Execution Flow:
${arch.executionPipeline
  .map(
    (p) => `// Stage ${p.stage}: [ ${p.nodeIds.map((id) => arch.nodes.find((n) => n.id === id)?.label || id).join(', ')} ]`
  )
  .join('\n')}

app.post('/api/lego/execute', async (req: Request, res: Response) => {
  const context: Record<string, any> = { input: req.body };

  try {
${arch.nodes
  .map((node) => {
    switch (node.type) {
      case 'login':
        return `    // [Block: ${node.label}] (${node.id})
    context['${node.id}_session'] = await authenticateSession({
      provider: ${JSON.stringify(node.config.provider || 'Google OAuth')},
      mfaRequired: ${node.config.mfaRequired ?? true}
    });`;
      case 'database':
        return `    // [Block: ${node.label}] (${node.id})
    context['${node.id}_data'] = await databaseQuery({
      table: ${JSON.stringify(node.config.table || 'records')},
      operation: ${JSON.stringify(node.config.operation || 'select')},
      params: context
    });`;
      case 'aiRequest':
        return `    // [Block: ${node.label}] (${node.id})
    context['${node.id}_ai'] = await invokeGeminiAI({
      model: ${JSON.stringify(node.config.model || 'gemini-2.5-flash')},
      systemInstruction: ${JSON.stringify(node.config.systemInstruction || '')},
      temperature: ${node.config.temperature ?? 0.7},
      input: context
    });`;
      case 'payment':
        return `    // [Block: ${node.label}] (${node.id})
    context['${node.id}_payment'] = await stripeCharge({
      planId: ${JSON.stringify(node.config.planId || 'pro_tier')},
      currency: ${JSON.stringify(node.config.currency || 'USD')}
    });`;
      case 'upload':
        return `    // [Block: ${node.label}] (${node.id})
    context['${node.id}_upload'] = await s3StorageClient({
      bucket: ${JSON.stringify(node.config.bucket || 'default-bucket')}
    });`;
      case 'condition':
        return `    // [Block: ${node.label}] (${node.id})
    const isConditionMet_${node.id.replace(/-/g, '_')} = evaluateCondition(context, ${JSON.stringify(
          node.config.fieldKey
        )});`;
      default:
        return `    // [Block: ${node.label}]
    // Custom block execution step`;
    }
  })
  .join('\n\n')}

    return res.status(200).json({
      status: 'success',
      buildVersion: '${arch.version}',
      output: context,
    });
  } catch (error: any) {
    console.error('Lego Flow Error:', error);
    return res.status(500).json({ status: 'failed', error: error.message });
  }
});

export default app;
`;
}
